name: Exercicio Um

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: date

  job2:
    name: Segundo Job
    runs-on: windows-latest

    steps:
      - name: Step 1
        run: "Get-Date"

  job3:
    name: Terceiro Job
    runs-on: macos-latest

    steps:
      - name: Step 1
        run: date

  job4:
    name: Quarto Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]

    steps:
      - name: Step final
        run: date
