# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - projetoFinal-Prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  buildAndTest:
    runs-on: ubuntu-latest
    
    env:
      ARTIFACT_NAME: node-app

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
  
  lintjob:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          prettier: true

  deploy-em-homolog:
    runs-on: ubuntu-latest
    env: 
       APP_NAME_HOMOLOG: projetoFinal-Homolog
       DB_URI: $${{ secrets.DB_URI_HOMOLOG }}
       
    needs: [buildAndTest, lintjob]
    environment:
      name: 'homolog'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME_HOMOLOG }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        run: MONGODB_URI=${{ env.DB_URI }} npm run devstart



  deploy-em-producao:
    runs-on: ubuntu-latest
    
    env:
      APP_NAME_PROD: projetoFinal-Prod
      DB_URI: $${{ secrets.DB_URI_PROD }}
      
    needs: deploy-em-homolog
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app

    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME_PROD }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_69a70517325f47f58873a2a6ad5e3e74 }}
        package: .
